name: flexify
description: "Polish your phone with Flexify's amazing set of wallpapers and widgets."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.2.1+7

environment:
  sdk: ^3.5.3

dependencies:
  android_intent_plus: ^5.3.0
  cached_network_image: ^3.4.1
  device_info_plus: ^11.1.0
  dio: ^5.7.0
  dynamic_color: ^1.7.0
  easy_localization: ^3.0.7+1
  firebase_analytics: ^11.3.5
  firebase_core: ^3.8.0
  firebase_messaging: ^15.2.7
  firebase_remote_config: ^5.3.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_local_notifications: ^19.2.1
  flutter_native_splash: ^2.4.3
  flutter_styled_toast: ^2.2.1
  image_gallery_saver_plus: ^4.0.1
  installed_apps: ^1.6.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  provider: ^6.1.2
  share_plus: ^11.0.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  sqflite: ^2.4.1
  url_launcher: ^6.3.1
  wallpaper_manager_plus: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  envied_generator: ^1.0.0
  build_runner: ^2.4.13

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff" # You can use a color or image for the background
  adaptive_icon_foreground: "assets/images/icon_adaptive.png" # For adaptive icons on Android

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#1c1e25"
  image: assets/images/icon_splash.png
  android_12:
    # image: assets/images/icon_splash.png
    color: "#ffffff"
    color_dark: "#1c1e25"
  web: false
  ios: false


flutter:
  uses-material-design: true

  fonts:
    - family: Oduda
      fonts:
        - asset: assets/fonts/oduda.otf
    - family: Oduda-Bold
      fonts:
        - asset: assets/fonts/oduda_bold.otf

  assets:
    - assets/images/
    - shorebird.yaml
    - assets/translations/