name: flexify
description: "Polish your phone with Flexify's amazing set of wallpapers and widgets."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  android_intent_plus: ^5.2.0
  cached_network_image: ^3.4.1
  device_info_plus: ^11.1.0
  dio: ^5.7.0
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^5.2.1
  flutter_styled_toast: ^2.2.1
  image: ^4.3.0
  image_gallery_saver_plus: ^3.0.5
  installed_apps: ^1.5.2
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  sqflite: ^2.4.1
  url_launcher: ^6.3.1
  wallpaper_manager_plus: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#d9d9d9" # You can use a color or image for the background
  adaptive_icon_foreground: "assets/images/icon_adaptive.png" # For adaptive icons on Android

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
